// -
//   ========================LICENSE_START=================================
//   O-RAN-SC
//   %%
//   Copyright (C) 2021-2022: Nordix Foundation
//   %%
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//   ========================LICENSE_END===================================
//

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	jobs "oransc.org/nonrtric/dmaapmediatorproducer/internal/jobs"
)

// JobsManager is an autogenerated mock type for the JobsManager type
type JobsManager struct {
	mock.Mock
}

// AddJobFromRESTCall provides a mock function with given fields: _a0
func (_m *JobsManager) AddJobFromRESTCall(_a0 jobs.JobInfo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(jobs.JobInfo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteJobFromRESTCall provides a mock function with given fields: jobId
func (_m *JobsManager) DeleteJobFromRESTCall(jobId string) {
	_m.Called(jobId)
}
